version: "3.4"

services:
  mubier:
    user: ${CONTAINER_UID}:${CONTAINER_GID}
    command: gunicorn --bind 0.0.0.0:8002 app:app
    working_dir: /mubier/mubier
    restart: on-failure
    volumes:
    - ".:/mubier"
  fetcher:
    user: ${CONTAINER_UID}:${CONTAINER_GID}
    image: mubier
    working_dir: /mubier/mubier
    command: python fetch.py
    container_name: mubier_fetcher
    restart: on-failure
    depends_on:
      - mubier
    volumes:
      - ".:/mubier"

