#!/usr/bin/env bash

BASE_DOCKER_COMPOSE_FILE="./docker-compose.yml"
DEV_DOCKER_COMPOSE_FILE="./docker-compose.development.yml"

CONTAINER_UID=$(id -u) CONTAINER_GID=$(id -g) docker-compose -f ${BASE_DOCKER_COMPOSE_FILE} -f ${DEV_DOCKER_COMPOSE_FILE} stop
CONTAINER_UID=$(id -u) CONTAINER_GID=$(id -g) docker-compose -f ${BASE_DOCKER_COMPOSE_FILE} -f ${DEV_DOCKER_COMPOSE_FILE} rm --force
CONTAINER_UID=$(id -u) CONTAINER_GID=$(id -g) docker-compose -f ${BASE_DOCKER_COMPOSE_FILE} -f ${DEV_DOCKER_COMPOSE_FILE} up -d --remove-orphans --build
CONTAINER_UID=$(id -u) CONTAINER_GID=$(id -g) docker-compose -f ${BASE_DOCKER_COMPOSE_FILE} -f ${DEV_DOCKER_COMPOSE_FILE} exec mubier bash
